name: Django REST Framework Build + Deployment

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "django-pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: 3.12.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # This is already up to date

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4  # Update to the latest version
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Run Tests
      run: |
        python manage.py test

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: django-artifact
        path: staticfiles

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true  # Enable GitHub Pages if not already enabled

    - name: Deploy to GitHub Pages 🚀
      if: github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4.0.5
      with:
        artifact_name: django-artifact
